"""WALKTO walks a player to a named place from wherever they stand.

It used to be a help topic and nothing more: HELP WALKTO listed the areas,
and typing WALKTO got "Huh?". The routes everybody publishes start at the
Oak Tree Square, which is no use to somebody standing anywhere else, so
the command finds its own way from the player's room and walks it a step
per half second through move_char -- every rule a walking player obeys
still applies, and a refusal ends the walk.

What it can walk to is area/walkto.dat, generated by
tools/build_directions.py from the same data as webadmin/directions.json:
the areas HELP WALKTO lists, every guild hall, the guild clerk, and every
guildmaster and trainer. The file tests here read files only; the live
tests boot a real server in a throwaway tree.
"""
from __future__ import annotations

import importlib.util
import json
import os
import re
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))

from live_mud import (  # noqa: E402
    LiveMud,
    create_character,
    login,
    patch_player_file,
    skip_reason,
)

SKIP = skip_reason()
PASSWORD = "Zwalker1"

TEMPLE = 4207                # not the Oak Tree Square, which every route starts from
RAKAR_ROOM = 2405            # Western Oak Tree Square: the weaponsmaster
NECRO_MASTER_ROOM = 4721     # Master's Chambers, behind the Morgue's guard
CAMELOT_LEDGE = 720          # down from here is a death trap
CAMELOT_DEATH_TRAP = 724     # The Yawning Depths, ROOM_DT


def read(*parts: str) -> str:
    return ROOT.joinpath(*parts).read_text(encoding="latin-1")


def load_builder():
    spec = importlib.util.spec_from_file_location(
        "build_directions", ROOT / "tools" / "build_directions.py")
    builder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(builder)
    return builder


class WalktoDataTests(unittest.TestCase):
    """The destinations, and that they are generated, not hand-kept."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.data = json.loads(
            (ROOT / "webadmin" / "directions.json").read_text(encoding="utf-8"))
        cls.dat_path = ROOT / "area" / "walkto.dat"
        cls.rows = [line.split("\t")
                    for line in cls.dat_path.read_text(encoding="latin-1").splitlines()
                    if line and not line.startswith("#")]

    def test_the_generator_reproduces_it(self) -> None:
        """A file that regenerates differently has been hand-edited."""
        before = self.dat_path.read_bytes()
        builder = load_builder()
        cwd = os.getcwd()
        os.chdir(ROOT)
        try:
            builder.write_walkto_data(self.data)
            after = self.dat_path.read_bytes()
        finally:
            self.dat_path.write_bytes(before)
            os.chdir(cwd)
        self.assertEqual(before, after,
                         "area/walkto.dat does not match its generator")

    def test_every_row_is_well_formed(self) -> None:
        kinds = {"place", "guild", "clerk", "trainer", "area"}
        for row in self.rows:
            self.assertEqual(6, len(row), row)
            self.assertIn(row[0], kinds, row)
            self.assertTrue(row[1].isdigit() and 0 < int(row[1]) < 32768, row)

    def test_every_published_area_route_is_a_destination(self) -> None:
        areas = {row[2] for row in self.rows if row[0] == "area"}
        for route in self.data["routes"]:
            self.assertIn(route.get("area_display") or route["area"], areas)

    def test_every_joinable_guild_hall_is_there(self) -> None:
        halls = {row[2] for row in self.rows if row[0] == "guild"}
        for hall in ("University of Magic", "Temple of Breas",
                     "Citadel of War", "House of Thieves",
                     "Palm of the Creator", "Morgue of Dresden"):
            self.assertTrue(any(name.startswith(hall) for name in halls), hall)
        self.assertTrue(any(row[0] == "clerk" and "Melancholy" in row[2]
                            for row in self.rows))

    def test_no_destination_is_a_death_trap(self) -> None:
        builder = load_builder()
        cwd = os.getcwd()
        os.chdir(ROOT)
        try:
            rooms = builder.load_world()
        finally:
            os.chdir(cwd)
        traps = {v for v, room in rooms.items() if "I" in room["flags"]}
        self.assertIn(CAMELOT_DEATH_TRAP, traps)
        named = {int(row[1]) for row in self.rows}
        self.assertEqual(set(), named & traps)


class TrainerDirectionsTests(unittest.TestCase):
    """The trainers list in directions.json, which the Mudlet package,
    the website and the Oracle read."""

    KEYS = ("name", "role", "class", "guild", "room", "vnum", "commands",
            "steps", "rooms_away", "members_only")

    @classmethod
    def setUpClass(cls) -> None:
        cls.data = json.loads(
            (ROOT / "webadmin" / "directions.json").read_text(encoding="utf-8"))
        cls.trainers = cls.data.get("trainers") or []

    def test_every_entry_carries_the_keys_the_clients_read(self) -> None:
        self.assertGreater(len(self.trainers), 40)
        for entry in self.trainers:
            for key in self.KEYS:
                self.assertIn(key, entry, entry.get("name"))
            self.assertIsInstance(entry["vnum"], int)

    def test_the_necro_guild_master_route(self) -> None:
        """The owner's own example: Master's Chambers, from the square."""
        master = next(e for e in self.trainers
                      if e["vnum"] == NECRO_MASTER_ROOM and "Master" in e["name"])
        self.assertEqual("r s 6;r w 2;r n 5", master["commands"])
        self.assertEqual("necro", master["members_only"])
        self.assertEqual("Necro Guild Master (Morgue of Dresden)", master["name"])

    def test_every_guildmaster_in_the_game_table_is_routed(self) -> None:
        """guildmaster_table in src/const.c is the authority, read straight
        from the C so the list cannot drift from it. Every master in it
        stands somewhere a player can walk today; one that stops doing so
        should be noticed, not silently dropped."""
        table = read("src", "const.c").split("guildmaster_table", 2)[-1]
        body = re.sub(r"/\*.*?\*/", " ", table.split("\n};", 1)[0], flags=re.S)
        vnums = {int(v) for v in re.findall(r"\{\s*(\d+)\s*,\s*CLASS_", body)}
        self.assertGreaterEqual(len(vnums), 46)
        listed = {e.get("mob") for e in self.trainers}
        self.assertEqual(set(), vnums - listed,
                         "guildmasters with no route")

    def test_routes_are_left_alone(self) -> None:
        self.assertEqual(self.data["counts"]["computed"],
                         len(self.data["routes"]))
        self.assertNotIn("trainer", {r.get("role") for r in self.data["routes"]})


class WalktoWiringTests(unittest.TestCase):
    def test_it_is_a_command_and_hides_no_social(self) -> None:
        interp = read("src", "interp.c")
        self.assertRegex(interp, r'\{\s*"walkto",\s*do_walkto,')
        # WAKE still owns WA.
        self.assertLess(interp.index('"wake"'), interp.index('"walkto"'))
        socials = read("area", "social.are")
        self.assertIsNone(re.search(r"^wal", socials, re.M))
        self.assertIn("src/walkto.c", read("CMakeLists.txt"))

    def test_typed_commands_stop_it_and_nothing_resumes_it(self) -> None:
        comm = read("src", "comm.c")
        hook = comm.index("walkto_interrupt( ch, d->incomm );")
        self.assertLess(hook, comm.index("interpret( ch, d->incomm );", hook))
        self.assertIn("walkto_clear( ch );", comm)
        self.assertIn("walkto_update( );", read("src", "update.c"))
        self.assertIn("walkto_load( );", read("src", "db.c"))

    def test_a_death_trap_is_refused_before_anything_else(self) -> None:
        src = read("src", "walkto.c")
        body = src.split("static bool walk_room_ok(", 1)[1].split("\n}\n", 1)[0]
        dt = body.index("ROOM_DT")
        self.assertLess(dt, body.index("can_see_room"))
        # And again at the step, whatever the search said.
        step = src.split("static void walkto_step(", 1)[1].split("\n}\n", 1)[0]
        self.assertIn("IS_SET(move.to->room_flags, ROOM_DT)", step)

    def test_help_documents_the_command(self) -> None:
        text = read("area", "routelist.are")
        self.assertIn("walkto <place>", text)
        self.assertIn("walkto stop", text)

    def test_the_file_ships_with_the_code(self) -> None:
        """Data the game reads at boot, not runtime state: not ignored, not
        excluded from a deploy, and copied into every test world."""
        self.assertNotIn("walkto", read(".gitignore"))
        deploy = read("deploy", "windows-vm", "toc-deploy")
        self.assertNotIn("walkto", deploy)
        self.assertNotIn("*.dat", deploy)
        self.assertIn("area/walkto.dat text eol=lf", read(".gitattributes"))


def run(client, command: str, settle: float = 1.2) -> str:
    mark = len(client.transcript)
    client.send(command)
    client.drain(settle)
    return client.transcript[mark:]


def wait_for(client, needle: str, seconds: float) -> str:
    mark = len(client.transcript)
    client.expect(needle, timeout=seconds)
    client.drain(0.3)
    return client.transcript[mark:]


@unittest.skipIf(SKIP is not None, SKIP or "")
class WalktoLiveTests(unittest.TestCase):
    def test_walking_stopping_and_refusing(self) -> None:
        with LiveMud() as mud:
            with mud.connect(timeout=120) as client:
                create_character(client, "Zwalker", PASSWORD)
                client.drain(1.0)
                client.send("quit")
                self.assertTrue(client.wait_closed(), "character did not leave")
            # A mortal, somewhere other than the Oak Tree Square, with the
            # hit points its level implies and the legs for a long walk.
            patch_player_file(mud, "Zwalker", Levl=20, Room=TEMPLE,
                              HMV="2000 2000 100 100 500 500")

            with mud.connect(timeout=120) as client:
                login(client, "Zwalker", PASSWORD)

                listing = run(client, "walkto")
                self.assertIn("Guild halls:", listing, listing)
                self.assertIn("University of Magic", listing)

                unknown = run(client, "walkto zzqxj")
                self.assertIn("nowhere called", unknown, unknown)

                # A warrior is no necromancer: the Morgue's guard would turn
                # them away, so WALKTO says so rather than walk them to him.
                refused = run(client, "walkto necro master")
                self.assertIn("Only necromancers of the necro guild", refused,
                              refused)

                # From the Temple to the weaponsmaster, and arriving.
                started = run(client, "walkto rakar", 0.8)
                self.assertIn("You set off for Rakar", started, started)
                walked = started + wait_for(client, "You have arrived at Rakar", 30)
                self.assertIn("Western Oak Tree Square", walked, walked)
                here = run(client, "look", 1.0)
                self.assertIn("Western Oak Tree Square", here, here)

                # WALKTO STOP ends it where it stands.
                run(client, "walkto moria", 0.4)
                stopped = run(client, "walkto stop", 3.0)
                self.assertIn("You stop walking.", stopped, stopped)
                self.assertNotIn("You have arrived", stopped)

                # So does any other command.
                run(client, "walkto moria", 0.4)
                other = run(client, "score", 2.5)
                self.assertIn("You stop walking.", other, other)
                self.assertNotIn("You have arrived", other)

                client.send("quit")
                self.assertTrue(client.wait_closed(), "character did not leave")

            # Staff may name a room by number, which is the only way to
            # ask for a death trap at all -- and it is still refused.
            patch_player_file(mud, "Zwalker", Levl=70, Room=CAMELOT_LEDGE)
            with mud.connect(timeout=120) as client:
                login(client, "Zwalker", PASSWORD)
                trap = run(client, "walkto %d" % CAMELOT_DEATH_TRAP)
                self.assertIn("no way to The Yawning Depths", trap, trap)
                self.assertNotIn("You set off", trap)


if __name__ == "__main__":
    unittest.main()
