#!/usr/bin/env bash

# Shared installer and launcher helpers. Source this file; do not execute it.

TOC_REPO_ROOT="${TOC_REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
TOC_ENV_FILE="$TOC_REPO_ROOT/.env"
TOC_DOCKER_WAIT_SECONDS="${TOC_DOCKER_WAIT_SECONDS:-300}"
TOC_GAME_WAIT_SECONDS="${TOC_GAME_WAIT_SECONDS:-180}"

toc_env_get() {
    local key="$1"
    local fallback="${2:-}"
    local value

    if [ ! -f "$TOC_ENV_FILE" ]; then
        printf '%s\n' "$fallback"
        return
    fi

    value="$(awk -F= -v wanted="$key" '
        $1 == wanted {
            sub(/^[^=]*=/, "")
            gsub(/\r$/, "")
            print
            exit
        }
    ' "$TOC_ENV_FILE")"
    printf '%s\n' "${value:-$fallback}"
}

toc_set_env() {
    local key="$1"
    local value="$2"
    local temp

    temp="$(mktemp "${TOC_ENV_FILE}.tmp.XXXXXX")"
    awk -v wanted="$key" -v replacement="$value" '
        BEGIN { found = 0 }
        $0 ~ "^[[:space:]]*" wanted "=" {
            if (!found) {
                print wanted "=" replacement
                found = 1
            }
            next
        }
        { print }
        END {
            if (!found) {
                print wanted "=" replacement
            }
        }
    ' "$TOC_ENV_FILE" > "$temp"
    mv "$temp" "$TOC_ENV_FILE"
}

toc_random_token() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
        return
    fi

    od -An -N32 -tx1 /dev/urandom | tr -d ' \n'
}

toc_configure_instance() {
    local network="${1:-preserve}"
    local token

    mkdir -p \
        "$TOC_REPO_ROOT/player" \
        "$TOC_REPO_ROOT/log" \
        "$TOC_REPO_ROOT/backups" \
        "$TOC_REPO_ROOT/gods" \
        "$TOC_REPO_ROOT/heroes" \
        "$TOC_REPO_ROOT/corpse"

    if [ ! -f "$TOC_ENV_FILE" ]; then
        token="$(toc_random_token)"
        umask 077
        cat > "$TOC_ENV_FILE" <<EOF
# Generated by the Times of Chaos installer. Do not commit this file.
MUD_BIND=127.0.0.1
MUD_PORT=9000
WEB_ADMIN_BIND=127.0.0.1
WEB_ADMIN_PORT=9001
WEB_ADMIN_ENABLED=1
TOC_UID=$(id -u)
TOC_GID=$(id -g)
WEB_ADMIN_TOKEN=$token
EOF
        echo "Created private runtime configuration at $TOC_ENV_FILE."
    else
        [ -n "$(toc_env_get MUD_BIND)" ] || toc_set_env MUD_BIND 127.0.0.1
        [ -n "$(toc_env_get MUD_PORT)" ] || toc_set_env MUD_PORT 9000
        [ -n "$(toc_env_get WEB_ADMIN_BIND)" ] || toc_set_env WEB_ADMIN_BIND 127.0.0.1
        [ -n "$(toc_env_get WEB_ADMIN_PORT)" ] || toc_set_env WEB_ADMIN_PORT 9001
        [ -n "$(toc_env_get WEB_ADMIN_ENABLED)" ] || toc_set_env WEB_ADMIN_ENABLED 1
        [ -n "$(toc_env_get TOC_UID)" ] || toc_set_env TOC_UID "$(id -u)"
        [ -n "$(toc_env_get TOC_GID)" ] || toc_set_env TOC_GID "$(id -g)"
        if [ -z "$(toc_env_get WEB_ADMIN_TOKEN)" ]; then
            toc_set_env WEB_ADMIN_TOKEN "$(toc_random_token)"
            echo "Added a random dashboard token to the existing .env file."
        else
            echo "Kept the existing dashboard token."
        fi
    fi

    case "$network" in
        local)  toc_set_env MUD_BIND 127.0.0.1 ;;
        public) toc_set_env MUD_BIND 0.0.0.0 ;;
        preserve) ;;
        *) echo "Unknown network mode: $network" >&2; return 2 ;;
    esac

    chmod 600 "$TOC_ENV_FILE" 2>/dev/null || true
}

toc_require_docker() {
    if ! command -v docker >/dev/null 2>&1; then
        echo "Docker was not found. Run ./install.sh first." >&2
        return 1
    fi
    if ! docker compose version >/dev/null 2>&1; then
        echo "Docker Compose v2 was not found. Run ./install.sh first." >&2
        return 1
    fi
}

toc_docker_ready() {
    docker info >/dev/null 2>&1
}

toc_start_docker() {
    local elapsed=0

    if toc_docker_ready; then
        return 0
    fi

    echo "Starting Docker..."
    if docker desktop --help >/dev/null 2>&1; then
        docker desktop start --detach --timeout "$TOC_DOCKER_WAIT_SECONDS" \
            >/dev/null 2>&1 || true
    fi

    if ! toc_docker_ready; then
        case "$(uname -s)" in
            # First launch can require an interactive Docker agreement.
            Darwin) open -a Docker 2>/dev/null || true ;;
            Linux)
                if command -v systemctl >/dev/null 2>&1; then
                    sudo systemctl start docker 2>/dev/null || true
                fi
                ;;
        esac
    fi

    while ! toc_docker_ready; do
        if [ "$elapsed" -ge "$TOC_DOCKER_WAIT_SECONDS" ]; then
            echo "Docker did not become ready within ${TOC_DOCKER_WAIT_SECONDS} seconds." >&2
            echo "Open Docker Desktop, complete any first-run prompts, then rerun this command." >&2
            return 1
        fi
        sleep 3
        elapsed=$((elapsed + 3))
    done
}

toc_wait_for_game() {
    local elapsed=0
    local container_id
    local health

    container_id="$(docker compose --project-directory "$TOC_REPO_ROOT" ps -q game)"
    if [ -z "$container_id" ]; then
        echo "The ToC container was not created." >&2
        return 1
    fi

    printf 'Waiting for Times of Chaos'
    while [ "$elapsed" -lt "$TOC_GAME_WAIT_SECONDS" ]; do
        health="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$container_id" 2>/dev/null || true)"
        case "$health" in
            healthy)
                printf ' ready.\n'
                return 0
                ;;
            unhealthy|exited|dead)
                printf ' failed.\n' >&2
                docker compose --project-directory "$TOC_REPO_ROOT" logs --tail 80 game >&2 || true
                return 1
                ;;
        esac
        printf '.'
        sleep 3
        elapsed=$((elapsed + 3))
    done

    printf ' timed out.\n' >&2
    docker compose --project-directory "$TOC_REPO_ROOT" logs --tail 80 game >&2 || true
    return 1
}

toc_print_endpoints() {
    local mud_bind
    local mud_port
    local web_port

    mud_bind="$(toc_env_get MUD_BIND 127.0.0.1)"
    mud_port="$(toc_env_get MUD_PORT 9000)"
    web_port="$(toc_env_get WEB_ADMIN_PORT 9001)"

    [ "$mud_bind" = "0.0.0.0" ] && mud_bind="this computer"

    echo
    echo "Times of Chaos is running."
    echo "MUD client: $mud_bind:$mud_port"
    echo "Dashboard:  http://127.0.0.1:$web_port"
    echo "Commands:   ./toc.sh status | logs | stop | restart | update"
}
