# Shared installer and launcher helpers. Dot-source this file; do not run it.

$script:TocRepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$script:TocEnvFile = Join-Path $script:TocRepoRoot '.env'
$script:TocDockerWaitSeconds = 300
$script:TocGameWaitSeconds = 180

function Get-TocEnvValue {
    param(
        [Parameter(Mandatory)]
        [string]$Name,
        [string]$Default = ''
    )

    if (-not (Test-Path -LiteralPath $script:TocEnvFile)) {
        return $Default
    }

    $match = Get-Content -LiteralPath $script:TocEnvFile |
        Where-Object { $_ -match "^$([regex]::Escape($Name))=" } |
        Select-Object -First 1
    if ($null -eq $match) {
        return $Default
    }

    $value = ($match -split '=', 2)[1]
    if ([string]::IsNullOrEmpty($value)) {
        return $Default
    }
    return $value
}

function Set-TocEnvValue {
    param(
        [Parameter(Mandatory)]
        [string]$Name,
        [Parameter(Mandatory)]
        [string]$Value
    )

    $lines = if (Test-Path -LiteralPath $script:TocEnvFile) {
        @(Get-Content -LiteralPath $script:TocEnvFile)
    } else {
        @()
    }

    $output = [Collections.Generic.List[string]]::new()
    $found = $false
    $pattern = "^$([regex]::Escape($Name))="
    foreach ($line in $lines) {
        if ($line -match $pattern) {
            if (-not $found) {
                $output.Add("$Name=$Value")
                $found = $true
            }
            continue
        }
        $output.Add($line)
    }
    if (-not $found) {
        $output.Add("$Name=$Value")
    }

    [IO.File]::WriteAllLines(
        $script:TocEnvFile,
        $output,
        [Text.UTF8Encoding]::new($false)
    )
}

function New-TocToken {
    $bytes = New-Object byte[] 32
    $generator = [Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($bytes)
    }
    finally {
        $generator.Dispose()
    }
    return -join ($bytes | ForEach-Object { $_.ToString('x2') })
}

function Initialize-TocInstance {
    param(
        [ValidateSet('Preserve', 'Local', 'Public')]
        [string]$Network = 'Preserve'
    )

    foreach ($directory in 'player', 'log', 'backups', 'gods', 'heroes', 'corpse') {
        New-Item -ItemType Directory `
            -Path (Join-Path $script:TocRepoRoot $directory) -Force | Out-Null
    }

    if (-not (Test-Path -LiteralPath $script:TocEnvFile)) {
        $lines = @(
            '# Generated by the Times of Chaos installer. Do not commit this file.'
            'MUD_BIND=127.0.0.1'
            'MUD_PORT=9000'
            'WEB_ADMIN_BIND=127.0.0.1'
            'WEB_ADMIN_PORT=9001'
            'WEB_ADMIN_ENABLED=1'
            'WEB_ADMIN_LOCAL_UNLOCK=1'
            'TOC_UID=1000'
            'TOC_GID=1000'
            "WEB_ADMIN_TOKEN=$(New-TocToken)"
        )
        [IO.File]::WriteAllLines(
            $script:TocEnvFile,
            $lines,
            [Text.UTF8Encoding]::new($false)
        )
        Write-Host 'Created private runtime configuration in .env.' -ForegroundColor Green
    } else {
        $defaults = [ordered]@{
            MUD_BIND = '127.0.0.1'
            MUD_PORT = '9000'
            WEB_ADMIN_BIND = '127.0.0.1'
            WEB_ADMIN_PORT = '9001'
            WEB_ADMIN_ENABLED = '1'
            WEB_ADMIN_LOCAL_UNLOCK = '1'
            TOC_UID = '1000'
            TOC_GID = '1000'
        }
        foreach ($entry in $defaults.GetEnumerator()) {
            if ([string]::IsNullOrEmpty((Get-TocEnvValue -Name $entry.Key))) {
                Set-TocEnvValue -Name $entry.Key -Value $entry.Value
            }
        }
        if ([string]::IsNullOrEmpty((Get-TocEnvValue -Name 'WEB_ADMIN_TOKEN'))) {
            Set-TocEnvValue -Name 'WEB_ADMIN_TOKEN' -Value (New-TocToken)
            Write-Host 'Added a random dashboard token to the existing .env file.' `
                -ForegroundColor Green
        } else {
            Write-Host 'Kept the existing dashboard token.' -ForegroundColor Green
        }
    }

    switch ($Network) {
        'Local' { Set-TocEnvValue -Name 'MUD_BIND' -Value '127.0.0.1' }
        'Public' { Set-TocEnvValue -Name 'MUD_BIND' -Value '0.0.0.0' }
    }
}

function Get-TocDockerExecutable {
    $command = Get-Command docker -ErrorAction SilentlyContinue
    if ($command) {
        return $command.Source
    }

    $candidates = @(
        (Join-Path $env:LOCALAPPDATA 'Programs\DockerDesktop\resources\bin\docker.exe')
        (Join-Path $env:LOCALAPPDATA 'Programs\Docker\Docker\resources\bin\docker.exe')
        (Join-Path $env:ProgramFiles 'Docker\Docker\resources\bin\docker.exe')
    )
    foreach ($candidate in $candidates) {
        if (Test-Path -LiteralPath $candidate) {
            return $candidate
        }
    }
    return $null
}

function Invoke-TocDocker {
    param(
        [Parameter(Mandatory)]
        [string[]]$ArgumentList,
        [switch]$AllowFailure,
        [switch]$Quiet
    )

    $docker = Get-TocDockerExecutable
    if (-not $docker) {
        throw 'Docker was not found. Run .\install.ps1 first.'
    }

    if ($Quiet) {
        & $docker @ArgumentList *> $null
    } else {
        & $docker @ArgumentList
    }
    $exitCode = $LASTEXITCODE
    if (-not $AllowFailure -and $exitCode -ne 0) {
        throw "docker $($ArgumentList -join ' ') failed with exit code $exitCode"
    }
    return $exitCode
}

function Test-TocDockerReady {
    $docker = Get-TocDockerExecutable
    if (-not $docker) {
        return $false
    }
    & $docker info *> $null
    return $LASTEXITCODE -eq 0
}

function Start-TocDocker {
    param([int]$WaitSeconds = $script:TocDockerWaitSeconds)

    if (Test-TocDockerReady) {
        return
    }

    Write-Host 'Starting Docker Desktop...' -ForegroundColor Cyan
    $docker = Get-TocDockerExecutable
    if ($docker) {
        & $docker desktop start --detach --timeout $WaitSeconds *> $null
    }

    if (-not (Test-TocDockerReady)) {
        $desktopCandidates = @(
            (Join-Path $env:LOCALAPPDATA 'Programs\DockerDesktop\Docker Desktop.exe')
            (Join-Path $env:LOCALAPPDATA 'Programs\Docker\Docker\Docker Desktop.exe')
            (Join-Path $env:ProgramFiles 'Docker\Docker\Docker Desktop.exe')
        )
        foreach ($desktop in $desktopCandidates) {
            if (Test-Path -LiteralPath $desktop) {
                # First launch can require an interactive Docker agreement.
                Start-Process -FilePath $desktop
                break
            }
        }
    }

    $deadline = [DateTime]::UtcNow.AddSeconds($WaitSeconds)
    while (-not (Test-TocDockerReady)) {
        if ([DateTime]::UtcNow -ge $deadline) {
            throw "Docker did not become ready within $WaitSeconds seconds. Open Docker Desktop, complete any first-run prompts, and rerun the command."
        }
        Start-Sleep -Seconds 3
    }
}

function Wait-TocGame {
    param([int]$WaitSeconds = $script:TocGameWaitSeconds)

    $docker = Get-TocDockerExecutable
    $containerId = & $docker compose --project-directory $script:TocRepoRoot `
        ps -q game | Select-Object -First 1
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($containerId)) {
        throw 'The ToC container was not created.'
    }

    Write-Host -NoNewline 'Waiting for Times of Chaos'
    $deadline = [DateTime]::UtcNow.AddSeconds($WaitSeconds)
    while ([DateTime]::UtcNow -lt $deadline) {
        $health = & $docker inspect --format `
            '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' `
            $containerId 2>$null
        switch ($health) {
            'healthy' {
                Write-Host ' ready.' -ForegroundColor Green
                return
            }
            { $_ -in 'unhealthy', 'exited', 'dead' } {
                Write-Host ' failed.' -ForegroundColor Red
                & $docker compose --project-directory $script:TocRepoRoot `
                    logs --tail 80 game
                throw "The ToC container entered the '$health' state."
            }
        }
        Write-Host -NoNewline '.'
        Start-Sleep -Seconds 3
    }

    Write-Host ' timed out.' -ForegroundColor Red
    & $docker compose --project-directory $script:TocRepoRoot logs --tail 80 game
    throw "Times of Chaos did not become healthy within $WaitSeconds seconds."
}

function Write-TocEndpoints {
    $mudBind = Get-TocEnvValue -Name 'MUD_BIND' -Default '127.0.0.1'
    $mudPort = Get-TocEnvValue -Name 'MUD_PORT' -Default '9000'
    $webPort = Get-TocEnvValue -Name 'WEB_ADMIN_PORT' -Default '9001'
    if ($mudBind -eq '0.0.0.0') {
        $mudBind = 'this computer'
    }

    Write-Host ''
    Write-Host 'Times of Chaos is running.' -ForegroundColor Green
    Write-Host "MUD port:   ${mudBind}:$mudPort"
    Write-Host "Web client: http://127.0.0.1:$webPort/client"
    Write-Host "Admin:      http://127.0.0.1:$webPort"
    Write-Host 'Commands:   .\toc.ps1 play | admin | status | logs | stop | restart | update'
}

function Open-TocClient {
    $webPort = Get-TocEnvValue -Name 'WEB_ADMIN_PORT' -Default '9001'
    Start-Process "http://127.0.0.1:$webPort/client"
}

function Open-TocDashboard {
    $webPort = Get-TocEnvValue -Name 'WEB_ADMIN_PORT' -Default '9001'
    Start-Process "http://127.0.0.1:$webPort"
}
